version: '3.8'
services:
  movies:
    image: nirajganjiwar24/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: nirajganjiwar24/paytrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: nirajganjiwar24/paydth:latest
    ports:
      - "83:80"
    deploy:
